### ISSUE TITLE
Can't Write/Read Int.MIN_VALUE as Bytes

### ISSUE THREAD

**Issue by SecurityInsanity** [Kotlin/kotlinx-io#12]
I'm attempting to write an integer as a series, of 4 bytes, and then read it back from a socket. However unfortunately while writing tests for code I seemed to have stumbled across a bug. Mainly the fact I can't seem to write an Integer.MIN_VALUE.  I've tried encoding in both BIG_ENDIAN/LITTLE_ENDIAN, and using different methods of encoding however all fail. Here, I've provided the simplest code I could think of to reproduce the error:

```kotlin
import kotlinx.coroutines.experimental.io.ByteReadChannel
import kotlinx.coroutines.experimental.runBlocking
import java.nio.ByteBuffer

fun main(args: Array<String>) {
        val min = Int.MIN_VALUE
        assert(min == -2147483648)
        val brc = ByteReadChannel(ByteBuffer.allocate(4).putInt(min))
        System.out.println(brc.availableForRead)
        val read = runBlocking { brc.readInt() }
        System.out.println(read)
}
```
Attempting to run this you should see: `0` printed to STDOUT, followed by an exception:

```
0

kotlinx.coroutines.experimental.channels.ClosedReceiveChannelException: EOF while an int expected
	at kotlinx.coroutines.experimental.io.ByteBufferChannel.readIntSuspend(ByteBufferChannel.kt:754)
	at kotlinx.coroutines.experimental.io.ByteBufferChannel.readInt(ByteBufferChannel.kt:748)
[...]
```

To be honest I'm not sure if this is an error with ByteReadChannel, or something else entirely. However, if this is the wrong place I'd be happy to file it elsewhere.

**Comment by SecurityInsanity** [comment]
I'm going to close this since it appears this is coming from ByteBuffer itself, however allocating 8 in the byte buffer makes the above code work. I'm not sure why exactly it needs an extra 4 bytes since kotlin says it's an int. However I can confirm that it's not a ByteReadChannel issue.
