### ISSUE TITLE
ClassCastException thrown when calling `Buffer.size`

### ISSUE THREAD

**Issue by JordanLongstaff** [Kotlin/kotlinx-io#400]
```
Caused by: java.lang.ClassCastException: class kotlin.Unit cannot be cast to class java.lang.Long (kotlin.Unit is in unnamed module of loader 'app'; java.lang.Long is in module java.base of loader 'bootstrap')
	at kotlinx.io.Buffer.getSize(Buffer.kt:60)
	at io.ktor.utils.io.core.BytePacketBuilderKt.getSize(BytePacketBuilder.kt:15)
	at io.ktor.utils.io.ByteWriteChannelKt.flushIfNeeded(ByteWriteChannel.kt:59)
	at io.ktor.utils.io.ByteWriteChannelOperationsKt.writeInt(ByteWriteChannelOperations.kt:31)
	at com.walkertribe.ian.protocol.core.PacketTestFixture$Companion.writePacketWithHeader(PacketTestFixture.kt:94)
	at com.walkertribe.ian.protocol.core.PacketTestFixture$Companion.prepare(PacketTestFixture.kt:87)
	at com.walkertribe.ian.protocol.core.PacketTestSpec$Server$runTest$2.invokeSuspend(PacketTestSpec.kt:212)
	at com.walkertribe.ian.protocol.core.PacketTestSpec$Server$runTest$2.invoke(PacketTestSpec.kt)
	at com.walkertribe.ian.protocol.core.PacketTestSpec$Server$runTest$2.invoke(PacketTestSpec.kt)
	at io.kotest.property.internal.ProptestKt$proptest$3$2.invokeSuspend(proptest.kt:49)
	at io.kotest.property.internal.ProptestKt$proptest$3$2.invoke(proptest.kt)
	at io.kotest.property.internal.ProptestKt$proptest$3$2.invoke(proptest.kt)
	at io.kotest.property.internal.TestKt.test(test.kt:49)
	at io.kotest.property.internal.ProptestKt.proptest(proptest.kt:40)
	at io.kotest.property.PropertyTest1Kt.checkAll(propertyTest1.kt:16)
	at io.kotest.property.PropertyTest1Kt.checkAllExt(propertyTest1.kt:11)
	... 442 more
```

**Comment by fzhinkin** [comment]
Hey @JordanLongstaff, thanks for reporting the issue. Could you please provide more details on how to reproduce it? Perhaps, there's a test you can share?

**Comment by JordanLongstaff** [comment]
Never mind, I found the problem. I'm using MockK, calling extension functions on a mock object and neglected to mock the extension functions.
